# Generated by Django 3.0.3 on 2020-04-19 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendomaticApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_count', models.IntegerField()),
            ],
            options={
                'verbose_name': 'coin',
                'verbose_name_plural': 'coins',
            },
        ),
    ]
